spring:
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017

  mongodb:
    embedded:
      version: 4.4.0

logging:
  level:
    org.springframework.data: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
