# .github/workflows/build.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start MongoDB
        run: docker compose -f "docker-compose.yml" up -d --build

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      # Execute Gradle commands in GitHub Actions workflows
      - uses: gradle/actions/setup-gradle@v4
        with:
          arguments: runOnGitHub

      # Send JaCoCo reports to codecov
      - run: bash <(curl -s https://codecov.io/bash)

      - name: Stop containers
        if: always()
        run: docker compose -f "docker-compose.yml" down
