# .github/workflows/build.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - name: Start MongoDB
        run: docker-compose -f "docker-compose.yml" up -d --build

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      # Execute Gradle commands in GitHub Actions workflows
      # => https://github.com/marketplace/actions/gradle-command
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: runOnGitHub
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      # Send JaCoCo reports to codecov
      - uses: codecov/codecov-action@v1

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
